### ISSUE TITLE
EFIgy database not being updated? Wrong command/version processed?

### ISSUE THREAD

**Issue by jelockwood** [duo-labs/EFIgy#27]
I can see that the EFIgy script does not list support for Mojave but it also appears that the supporting database has not been updated for the latest High Sierra builds either.

```
./EFIgyLite_cli.py 

EFIgyLite API information:
	Server: https://api.efigy.io
	API Version: 0.2
	Updated On: Mar 1 2018, 22:25


--------------------------------------------------------------------------------
Endpoint: 127.0.0.1
	# Enumerated system information (This data will be sent to the API in order to determine your correct EFI version):

	Hashed SysUUID   : d9607c33fcd75578a5b7440ba5e74cef2fbe7862e97d4976a97c63f6861a7d1a
	Hardware Version : MacBookPro11,4
	EFI Version      : 187.0.0
	SMC Version      : 2.29f24
	Board-ID         : Mac-06F11FD93F0323C5
	OS Version       : 10.13.6
	Build Number     : 17G3025

[?] Do you want to continue and submit this request? [Y/N]  y

	# Results:

	EFI firmware version check:
		[-] ATTENTION - You are running an unexpected firmware version given the model of your system (MacBookPro11,4) and OS build you have installed (17G3025). Your firmware is 187.0.0, the firmware we expected to see is MBP114.0184.B00.


	Highest build number check:
		[-] ATTENTION - You are NOT running the latest release build number of your OS version (10.13.6). Your build number is 17G3025, the latest release build number is 17G65

	Up-to-date OS check:
		[+] SUCCESS - You are running the latest major/minor/micro version of the OS you have installed (10.13.6)
--------------------------------------------------------------------------------
```

Issue 1
Clearly build 17G3025 is newer than 17G65 contrary to the above incorrect report. Build 17G3025 is the one with the latest Apple Security Update for High Sierra.

Issue 2
It seems EFIgy is still looking at the older source of EFI version as returned for example by this command

`system_profiler SPHardwareDataType | grep -i "Version" | awk -F ':' '{print $1 $2}'`
or
`echo "$(ioreg -d 3 -p IODeviceTree -n rom | awk -F\" '/version/{print $4}')"`

It is possible to get the older style firmware version via a different command

```
/usr/libexec/firmwarecheckers/eficheck/eficheck --integrity-check
EFI Version: MBP114.88Z.0185.B00.1809171422
Primary allowlist version match found. No changes detected in primary hashes.
```

However according to this article - https://eclecticlight.co/2018/10/31/which-efi-firmware-should-your-mac-be-using-version-3/ this does not work on T2 equipped Macs.

It would therefore seem that if there is still to be a means of checking EFI versions the current script (and database) needs urgently updating.

**Comment by n8felton** [comment]
I'm also wondering if there are any plans to continue to support this tool and/or the database/API that it uses.

**Comment by alvarnell** [comment]
I ask the same question when the GUI Tool was updated a few weeks ago and was assured that updating the database would be next, but hasn't happened yet. https://github.com/duo-labs/EFIgy-GUI/issues/5

**Comment by futureimperfect** [comment]
Hi @jelockwood, @n8felton, and @alvarnell,

Sorry for the delay. This should be resolved now, but feel free to reopen if not. The database and client have been updated.

Thanks!
