### ISSUE TITLE
Unsupported version of macOS detected '10.13'

### ISSUE THREAD

**Issue by vielmetti** [duo-labs/EFIgy#4]
If you are using 10.13 you'll currently get this error message, as referenced in https://github.com/duo-labs/EFIgy/issues/1#issuecomment-334033244

**Comment by MyNameIsMeerkat** [comment]
Thanks for the note, but as noted in the Readme the dataset (and the research in general)  only covers 10.10-10.12. It will be updated with data for 10.13 in due course but with Ekoparty and travel overlapping with the 10.13 release we haven't had time to get the analysis done and into the EFIgy dataset as yet. 
We will add in 10.13 data once that analysis has been completed and verified.
