### ISSUE TITLE
High Sierra firmware update not found

### ISSUE THREAD

**Issue by SecuritySpread** [duo-labs/EFIgy#5]
Hardware Version : MacPro5,1
	Boot ROM Version : MP51.0084.B00
	SMC Version      : 1.39f11
	Board-ID         : Mac-F221BEC8
	OS Version       : 10.12.6
	Build Number     : 16G29

EFI firmware version check:
	[-] ATTENTION - Your Mac model (MacPro5,1) does not seem to have had any EFI updates released for it :'(

During the High Sierra install the firmware of the machine was updated. I went back to 10.12.6 Sierra but the new firmware should still be in place.

Thanks!

**Comment by MyNameIsMeerkat** [comment]
Thanks for the note, but as noted in the Readme the dataset (and the research in general) only covers 10.10-10.12. It will be updated with data for 10.13 in due course but with Ekoparty and travel overlapping with the 10.13 release we haven't had time to get the analysis done and into the EFIgy dataset as yet.
We will add in 10.13 data once that analysis has been completed and verified.

**Comment by MyNameIsMeerkat** [comment]
More generally I am not clear what the best way to address updated firmware but subsequently downgraded OS is so going to think on it a little more. It may just be messaging that says you have *newer* firmware than expected. 

I'll look into addressing this as part of the changes we will be making for 10.13 support.

Thanks for raising this

**Comment by Piker-Alpha** [comment]
@SecuritySpread,

What do you get when you run:
```
/usr/libexec/efiupdater
```

**Comment by SecuritySpread** [comment]
/usr/libexec/efiupdater
Raw EFI Version string: MP51.88Z.0084.B00.1708080528
EFI currentVersion: [0000000000840000]
EFI updateVersion:  [0000000000000000]

**Comment by Piker-Alpha** [comment]
@SecuritySpread,

Just what I expected. The value of updateVersion tells us that there is no update. You're running the latest EFI firmware, that came with High Sierra. And it didn't downgrade the EFI to an older version. Which is good.

Thanks

**Comment by justPaulo** [comment]
[pnascim@MacMini-do-Paulo ~]$ python /Users/pnascim/Downloads/EFIgy-master/EFIgyLite_cli.py

EFIgyLite API Information:
	API Version: 0.2
	Updated On: Oct 3 2017, 16:44


Enumerated system informaton (This data will be sent to the API in order to determine your correct EFI version): 
	Hashed SysUUID   : ef7a45343357f68d9dcaf78844152afa6c396664fb9169b71a160cb91767d092
	Hardware Version : Macmini6,2
	Boot ROM Version : MM61.0106.B1F			<— EFI firmware version before High-Sierra (10.13)
	SMC Version      : 2.8f0
	Board-ID         : Mac-F65AE981FFA204ED
	OS Version       : 10.12.6
	Build Number     : 16G29

[?] Do you want to continue and submit this request? [Y/N]  Y

EFI firmware version check:
	[-] ATTENTION - You are running an unexpected firmware version given the model of your system (Macmini6,2) and OS build you have installed (16G29). Your firmware MM61.0106.B1F, expected firmware MM62.0106.B1F.
Update your firmware!!

Highest build number check:
	[+] SUCCESS - You are running the latest build number (16G29) of the OS version you have installed (10.12.6)

Up-to-date OS check:
	[+] SUCCESS - You are running the latest major/minor/micro version of the OS you have installed (10.12.6)

---

New firmware version (after High-Sierra upgrade):  **MM61**.88Z.**010B**.**B00**.1708080649

**Comment by MyNameIsMeerkat** [comment]
As of commit 798116c there is now initial 10.13.x support in the dataset and firmware that appears newer than expected is better messaged to the user.
